import type { Metadata } from "next";
import { Inter, Roboto, Noto_Serif } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const robot = Roboto({ subsets: ["latin"], weight: ["400", "700"]});
const noto = Inter({ subsets: ["latin"], weight: ["400", "700"]});

export const metadata: Metadata = {
  title: "X. It's what's happening / X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={[inter.className, robot.className, noto.className].join(" ")}>{children}</body>
    </html>
  );
}
